import base64
import json
import uuid
from datetime import datetime

print('Loading function')

# Given mappings
location_mapping = {
'1': 'EWR',
'2': 'Queens',
'3': 'Bronx',
'4': 'Manhattan',
'5': 'Staten Island',
'6': 'Staten Island',
'7': 'Queens',
'8': 'Queens',
'9': 'Queens',
'10': 'Queens',
'11': 'Brooklyn',
'12': 'Manhattan',
'13': 'Manhattan',
'14': 'Brooklyn',
'15': 'Queens',
'16': 'Queens',
'17': 'Brooklyn',
'18': 'Bronx',
'19': 'Queens',
'20': 'Bronx',
'21': 'Brooklyn',
'22': 'Brooklyn',
'23': 'Staten Island',
'24': 'Manhattan',
'25': 'Brooklyn',
'26': 'Brooklyn',
'27': 'Queens',
'28': 'Queens',
'29': 'Brooklyn',
'30': 'Queens',
'31': 'Bronx',
'32': 'Bronx',
'33': 'Brooklyn',
'34': 'Brooklyn',
'35': 'Brooklyn',
'36': 'Brooklyn',
'37': 'Brooklyn',
'38': 'Queens',
'39': 'Brooklyn',
'40': 'Brooklyn',
'41': 'Manhattan',
'42': 'Manhattan',
'43': 'Manhattan',
'44': 'Staten Island',
'45': 'Manhattan',
'46': 'Bronx',
'47': 'Bronx',
'48': 'Manhattan',
'49': 'Brooklyn',
'50': 'Manhattan',
'51': 'Bronx',
'52': 'Brooklyn',
'53': 'Queens',
'54': 'Brooklyn',
'55': 'Brooklyn',
'56': 'Queens',
'57': 'Queens',
'58': 'Bronx',
'59': 'Bronx',
'60': 'Bronx',
'61': 'Brooklyn',
'62': 'Brooklyn',
'63': 'Brooklyn',
'64': 'Queens',
'65': 'Brooklyn',
'66': 'Brooklyn',
'67': 'Brooklyn',
'68': 'Manhattan',
'69': 'Bronx',
'70': 'Queens',
'71': 'Brooklyn',
'72': 'Brooklyn',
'73': 'Queens',
'74': 'Manhattan',
'75': 'Manhattan',
'76': 'Brooklyn',
'77': 'Brooklyn',
'78': 'Bronx',
'79': 'Manhattan',
'80': 'Brooklyn',
'81': 'Bronx',
'82': 'Queens',
'83': 'Queens',
'84': 'Staten Island',
'85': 'Brooklyn',
'86': 'Queens',
'87': 'Manhattan',
'88': 'Manhattan',
'89': 'Brooklyn',
'90': 'Manhattan',
'91': 'Brooklyn',
'92': 'Queens',
'93': 'Queens',
'94': 'Bronx',
'95': 'Queens',
'96': 'Queens',
'97': 'Brooklyn',
'98': 'Queens',
'99': 'Staten Island',
'100': 'Manhattan',
'101': 'Queens',
'102': 'Queens',
'103': 'Manhattan',
'104': 'Manhattan',
'105': 'Manhattan',
'106': 'Brooklyn',
'107': 'Manhattan',
'108': 'Brooklyn',
'109': 'Staten Island',
'110': 'Staten Island',
'111': 'Brooklyn',
'112': 'Brooklyn',
'113': 'Manhattan',
'114': 'Manhattan',
'115': 'Staten Island',
'116': 'Manhattan',
'117': 'Queens',
'118': 'Staten Island',
'119': 'Bronx',
'120': 'Manhattan',
'121': 'Queens',
'122': 'Queens',
'123': 'Brooklyn',
'124': 'Queens',
'125': 'Manhattan',
'126': 'Bronx',
'127': 'Manhattan',
'128': 'Manhattan',
'129': 'Queens',
'130': 'Queens',
'131': 'Queens',
'132': 'Queens',
'133': 'Brooklyn',
'134': 'Queens',
'135': 'Queens',
'136': 'Bronx',
'137': 'Manhattan',
'138': 'Queens',
'139': 'Queens',
'140': 'Manhattan',
'141': 'Manhattan',
'142': 'Manhattan',
'143': 'Manhattan',
'144': 'Manhattan',
'145': 'Queens',
'146': 'Queens',
'147': 'Bronx',
'148': 'Manhattan',
'149': 'Brooklyn',
'150': 'Brooklyn',
'151': 'Manhattan',
'152': 'Manhattan',
'153': 'Manhattan',
'154': 'Brooklyn',
'155': 'Brooklyn',
'156': 'Staten Island',
'157': 'Queens',
'158': 'Manhattan',
'159': 'Bronx',
'160': 'Queens',
'161': 'Manhattan',
'162': 'Manhattan',
'163': 'Manhattan',
'164': 'Manhattan',
'165': 'Brooklyn',
'166': 'Manhattan',
'167': 'Bronx',
'168': 'Bronx',
'169': 'Bronx',
'170': 'Manhattan',
'171': 'Queens',
'172': 'Staten Island',
'173': 'Queens',
'174': 'Bronx',
'175': 'Queens',
'176': 'Staten Island',
'177': 'Brooklyn',
'178': 'Brooklyn',
'179': 'Queens',
'180': 'Queens',
'181': 'Brooklyn',
'182': 'Bronx',
'183': 'Bronx',
'184': 'Bronx',
'185': 'Bronx',
'186': 'Manhattan',
'187': 'Staten Island',
'188': 'Brooklyn',
'189': 'Brooklyn',
'190': 'Brooklyn',
'191': 'Queens',
'192': 'Queens',
'193': 'Queens',
'194': 'Manhattan',
'195': 'Brooklyn',
'196': 'Queens',
'197': 'Queens',
'198': 'Queens',
'199': 'Bronx',
'200': 'Bronx',
'201': 'Queens',
'202': 'Manhattan',
'203': 'Queens',
'204': 'Staten Island',
'205': 'Queens',
'206': 'Staten Island',
'207': 'Queens',
'208': 'Bronx',
'209': 'Manhattan',
'210': 'Brooklyn',
'211': 'Manhattan',
'212': 'Bronx',
'213': 'Bronx',
'214': 'Staten Island',
'215': 'Queens',
'216': 'Queens',
'217': 'Brooklyn',
'218': 'Queens',
'219': 'Queens',
'220': 'Bronx',
'221': 'Staten Island',
'222': 'Brooklyn',
'223': 'Queens',
'224': 'Manhattan',
'225': 'Brooklyn',
'226': 'Queens',
'227': 'Brooklyn',
'228': 'Brooklyn',
'229': 'Manhattan',
'230': 'Manhattan',
'231': 'Manhattan',
'232': 'Manhattan',
'233': 'Manhattan',
'234': 'Manhattan',
'235': 'Bronx',
'236': 'Manhattan',
'237': 'Manhattan',
'238': 'Manhattan',
'239': 'Manhattan',
'240': 'Bronx',
'241': 'Bronx',
'242': 'Bronx',
'243': 'Manhattan',
'244': 'Manhattan',
'245': 'Staten Island',
'246': 'Manhattan',
'247': 'Bronx',
'248': 'Bronx',
'249': 'Manhattan',
'250': 'Bronx',
'251': 'Staten Island',
'252': 'Queens',
'253': 'Queens',
'254': 'Bronx',
'255': 'Brooklyn',
'256': 'Brooklyn',
'257': 'Brooklyn',
'258': 'Queens',
'259': 'Bronx',
'260': 'Queens',
'261': 'Manhattan',
'262': 'Manhattan',
'263': 'Manhattan'}

Zone_mapping = {
'1': 'Newark Airport',
'2': 'Jamaica Bay',
'3': 'Allerton/Pelham Gardens',
'4': 'Alphabet City',
'5': 'Arden Heights',
'6': 'Arrochar/Fort Wadsworth',
'7': 'Astoria',
'8': 'Astoria Park',
'9': 'Auburndale',
'10': 'Baisley Park',
'11': 'Bath Beach',
'12': 'Battery Park',
'13': 'Battery Park City',
'14': 'Bay Ridge',
'15': 'Bay Terrace/Fort Totten',
'16': 'Bayside',
'17': 'Bedford',
'18': 'Bedford Park',
'19': 'Bellerose',
'20': 'Belmont',
'21': 'Bensonhurst East',
'22': 'Bensonhurst West',
'23': 'Bloomfield/Emerson Hill',
'24': 'Bloomingdale',
'25': 'Boerum Hill',
'26': 'Borough Park',
'27': 'Breezy Point/Fort Tilden/Riis Beach',
'28': 'Briarwood/Jamaica Hills',
'29': 'Brighton Beach',
'30': 'Broad Channel',
'31': 'Bronx Park',
'32': 'Bronxdale',
'33': 'Brooklyn Heights',
'34': 'Brooklyn Navy Yard',
'35': 'Brownsville',
'36': 'Bushwick North',
'37': 'Bushwick South',
'38': 'Cambria Heights',
'39': 'Canarsie',
'40': 'Carroll Gardens',
'41': 'Central Harlem',
'42': 'Central Harlem North',
'43': 'Central Park',
'44': 'Charleston/Tottenville',
'45': 'Chinatown',
'46': 'City Island',
'47': 'Claremont/Bathgate',
'48': 'Clinton East',
'49': 'Clinton Hill',
'50': 'Clinton West',
'51': 'Co-Op City',
'52': 'Cobble Hill',
'53': 'College Point',
'54': 'Columbia Street',
'55': 'Coney Island',
'56': 'Corona',
'57': 'Corona',
'58': 'Country Club',
'59': 'Crotona Park',
'60': 'Crotona Park East',
'61': 'Crown Heights North',
'62': 'Crown Heights South',
'63': 'Cypress Hills',
'64': 'Douglaston',
'65': 'Downtown Brooklyn/MetroTech',
'66': 'DUMBO/Vinegar Hill',
'67': 'Dyker Heights',
'68': 'East Chelsea',
'69': 'East Concourse/Concourse Village',
'70': 'East Elmhurst',
'71': 'East Flatbush/Farragut',
'72': 'East Flatbush/Remsen Village',
'73': 'East Flushing',
'74': 'East Harlem North',
'75': 'East Harlem South',
'76': 'East New York',
'77': 'East New York/Pennsylvania Avenue',
'78': 'East Tremont',
'79': 'East Village',
'80': 'East Williamsburg',
'81': 'Eastchester',
'82': 'Elmhurst',
'83': 'Elmhurst/Maspeth',
'84': 'Eltingville/Annadale/Princes Bay',
'85': 'Erasmus',
'86': 'Far Rockaway',
'87': 'Financial District North',
'88': 'Financial District South',
'89': 'Flatbush/Ditmas Park',
'90': 'Flatiron',
'91': 'Flatlands',
'92': 'Flushing',
'93': 'Flushing Meadows-Corona Park',
'94': 'Fordham South',
'95': 'Forest Hills',
'96': 'Forest Park/Highland Park',
'97': 'Fort Greene',
'98': 'Fresh Meadows',
'99': 'Freshkills Park',
'100': 'Garment District',
'101': 'Glen Oaks',
'102': 'Glendale',
'103': 'Governors Island/Ellis Island/Liberty Island',
'104': 'Governors Island/Ellis Island/Liberty Island',
'105': 'Governors Island/Ellis Island/Liberty Island',
'106': 'Gowanus',
'107': 'Gramercy',
'108': 'Gravesend',
'109': 'Great Kills',
'110': 'Great Kills Park',
'111': 'Green-Wood Cemetery',
'112': 'Greenpoint',
'113': 'Greenwich Village North',
'114': 'Greenwich Village South',
'115': 'Grymes Hill/Clifton',
'116': 'Hamilton Heights',
'117': 'Hammels/Arverne',
'118': 'Heartland Village/Todt Hill',
'119': 'Highbridge',
'120': 'Highbridge Park',
'121': 'Hillcrest/Pomonok',
'122': 'Hollis',
'123': 'Homecrest',
'124': 'Howard Beach',
'125': 'Hudson Sq',
'126': 'Hunts Point',
'127': 'Inwood',
'128': 'Inwood Hill Park',
'129': 'Jackson Heights',
'130': 'Jamaica',
'131': 'Jamaica Estates',
'132': 'JFK Airport',
'133': 'Kensington',
'134': 'Kew Gardens',
'135': 'Kew Gardens Hills',
'136': 'Kingsbridge Heights',
'137': 'Kips Bay',
'138': 'LaGuardia Airport',
'139': 'Laurelton',
'140': 'Lenox Hill East',
'141': 'Lenox Hill West',
'142': 'Lincoln Square East',
'143': 'Lincoln Square West',
'144': 'Little Italy/NoLiTa',
'145': 'Long Island City/Hunters Point',
'146': 'Long Island City/Queens Plaza',
'147': 'Longwood',
'148': 'Lower East Side',
'149': 'Madison',
'150': 'Manhattan Beach',
'151': 'Manhattan Valley',
'152': 'Manhattanville',
'153': 'Marble Hill',
'154': 'Marine Park/Floyd Bennett Field',
'155': 'Marine Park/Mill Basin',
'156': 'Mariners Harbor',
'157': 'Maspeth',
'158': 'Meatpacking/West Village West',
'159': 'Melrose South',
'160': 'Middle Village',
'161': 'Midtown Center',
'162': 'Midtown East',
'163': 'Midtown North',
'164': 'Midtown South',
'165': 'Midwood',
'166': 'Morningside Heights',
'167': 'Morrisania/Melrose',
'168': 'Mott Haven/Port Morris',
'169': 'Mount Hope',
'170': 'Murray Hill',
'171': 'Murray Hill-Queens',
'172': 'New Dorp/Midland Beach',
'173': 'North Corona',
'174': 'Norwood',
'175': 'Oakland Gardens',
'176': 'Oakwood',
'177': 'Ocean Hill',
'178': 'Ocean Parkway South',
'179': 'Old Astoria',
'180': 'Ozone Park',
'181': 'Park Slope',
'182': 'Parkchester',
'183': 'Pelham Bay',
'184': 'Pelham Bay Park',
'185': 'Pelham Parkway',
'186': 'Penn Station/Madison Sq West',
'187': 'Port Richmond',
'188': 'Prospect-Lefferts Gardens',
'189': 'Prospect Heights',
'190': 'Prospect Park',
'191': 'Queens Village',
'192': 'Queensboro Hill',
'193': 'Queensbridge/Ravenswood',
'194': 'Randalls Island',
'195': 'Red Hook',
'196': 'Rego Park',
'197': 'Richmond Hill',
'198': 'Ridgewood',
'199': 'Rikers Island',
'200': 'Riverdale/North Riverdale/Fieldston',
'201': 'Rockaway Park',
'202': 'Roosevelt Island',
'203': 'Rosedale',
'204': 'Rossville/Woodrow',
'205': 'Saint Albans',
'206': 'Saint George/New Brighton',
'207': 'Saint Michaels Cemetery/Woodside',
'208': 'Schuylerville/Edgewater Park',
'209': 'Seaport',
'210': 'Sheepshead Bay',
'211': 'SoHo',
'212': 'Soundview/Bruckner',
'213': 'Soundview/Castle Hill',
'214': 'South Beach/Dongan Hills',
'215': 'South Jamaica',
'216': 'South Ozone Park',
'217': 'South Williamsburg',
'218': 'Springfield Gardens North',
'219': 'Springfield Gardens South',
'220': 'Spuyten Duyvil/Kingsbridge',
'221': 'Stapleton',
'222': 'Starrett City',
'223': 'Steinway',
'224': 'Stuy Town/Peter Cooper Village',
'225': 'Stuyvesant Heights',
'226': 'Sunnyside',
'227': 'Sunset Park East',
'228': 'Sunset Park West',
'229': 'Sutton Place/Turtle Bay North',
'230': 'Times Sq/Theatre District',
'231': 'TriBeCa/Civic Center',
'232': 'Two Bridges/Seward Park',
'233': 'UN/Turtle Bay South',
'234': 'Union Sq',
'235': 'University Heights/Morris Heights',
'236': 'Upper East Side North',
'237': 'Upper East Side South',
'238': 'Upper West Side North',
'239': 'Upper West Side South',
'240': 'Van Cortlandt Park',
'241': 'Van Cortlandt Village',
'242': 'Van Nest/Morris Park',
'243': 'Washington Heights North',
'244': 'Washington Heights South',
'245': 'West Brighton',
'246': 'West Chelsea/Hudson Yards',
'247': 'West Concourse',
'248': 'West Farms/Bronx River',
'249': 'West Village',
'250': 'Westchester Village/Unionport',
'251': 'Westerleigh',
'252': 'Whitestone',
'253': 'Willets Point',
'254': 'Williamsbridge/Olinville',
'255': 'Williamsburg (North Side)',
'256': 'Williamsburg (South Side)',
'257': 'Windsor Terrace',
'258': 'Woodhaven',
'259': 'Woodlawn/Wakefield',
'260': 'Woodside',
'261': 'World Trade Center',
'262': 'Yorkville East',
'263': 'Yorkville West'}


service_zone_mapping = {
'1': 'EWR',
'2': 'Boro Zone',
'3': 'Boro Zone',
'4': 'Yellow Zone',
'5': 'Boro Zone',
'6': 'Boro Zone',
'7': 'Boro Zone',
'8': 'Boro Zone',
'9': 'Boro Zone',
'10': 'Boro Zone',
'11': 'Boro Zone',
'12': 'Yellow Zone',
'13': 'Yellow Zone',
'14': 'Boro Zone',
'15': 'Boro Zone',
'16': 'Boro Zone',
'17': 'Boro Zone',
'18': 'Boro Zone',
'19': 'Boro Zone',
'20': 'Boro Zone',
'21': 'Boro Zone',
'22': 'Boro Zone',
'23': 'Boro Zone',
'24': 'Yellow Zone',
'25': 'Boro Zone',
'26': 'Boro Zone',
'27': 'Boro Zone',
'28': 'Boro Zone',
'29': 'Boro Zone',
'30': 'Boro Zone',
'31': 'Boro Zone',
'32': 'Boro Zone',
'33': 'Boro Zone',
'34': 'Boro Zone',
'35': 'Boro Zone',
'36': 'Boro Zone',
'37': 'Boro Zone',
'38': 'Boro Zone',
'39': 'Boro Zone',
'40': 'Boro Zone',
'41': 'Boro Zone',
'42': 'Boro Zone',
'43': 'Yellow Zone',
'44': 'Boro Zone',
'45': 'Yellow Zone',
'46': 'Boro Zone',
'47': 'Boro Zone',
'48': 'Yellow Zone',
'49': 'Boro Zone',
'50': 'Yellow Zone',
'51': 'Boro Zone',
'52': 'Boro Zone',
'53': 'Boro Zone',
'54': 'Boro Zone',
'55': 'Boro Zone',
'56': 'Boro Zone',
'57': 'Boro Zone',
'58': 'Boro Zone',
'59': 'Boro Zone',
'60': 'Boro Zone',
'61': 'Boro Zone',
'62': 'Boro Zone',
'63': 'Boro Zone',
'64': 'Boro Zone',
'65': 'Boro Zone',
'66': 'Boro Zone',
'67': 'Boro Zone',
'68': 'Yellow Zone',
'69': 'Boro Zone',
'70': 'Boro Zone',
'71': 'Boro Zone',
'72': 'Boro Zone',
'73': 'Boro Zone',
'74': 'Boro Zone',
'75': 'Boro Zone',
'76': 'Boro Zone',
'77': 'Boro Zone',
'78': 'Boro Zone',
'79': 'Yellow Zone',
'80': 'Boro Zone',
'81': 'Boro Zone',
'82': 'Boro Zone',
'83': 'Boro Zone',
'84': 'Boro Zone',
'85': 'Boro Zone',
'86': 'Boro Zone',
'87': 'Yellow Zone',
'88': 'Yellow Zone',
'89': 'Boro Zone',
'90': 'Yellow Zone',
'91': 'Boro Zone',
'92': 'Boro Zone',
'93': 'Boro Zone',
'94': 'Boro Zone',
'95': 'Boro Zone',
'96': 'Boro Zone',
'97': 'Boro Zone',
'98': 'Boro Zone',
'99': 'Boro Zone',
'100': 'Yellow Zone',
'101': 'Boro Zone',
'102': 'Boro Zone',
'103': 'Yellow Zone',
'104': 'Yellow Zone',
'105': 'Yellow Zone',
'106': 'Boro Zone',
'107': 'Yellow Zone',
'108': 'Boro Zone',
'109': 'Boro Zone',
'110': 'Boro Zone',
'111': 'Boro Zone',
'112': 'Boro Zone',
'113': 'Yellow Zone',
'114': 'Yellow Zone',
'115': 'Boro Zone',
'116': 'Boro Zone',
'117': 'Boro Zone',
'118': 'Boro Zone',
'119': 'Boro Zone',
'120': 'Boro Zone',
'121': 'Boro Zone',
'122': 'Boro Zone',
'123': 'Boro Zone',
'124': 'Boro Zone',
'125': 'Yellow Zone',
'126': 'Boro Zone',
'127': 'Boro Zone',
'128': 'Boro Zone',
'129': 'Boro Zone',
'130': 'Boro Zone',
'131': 'Boro Zone',
'132': 'Airports',
'133': 'Boro Zone',
'134': 'Boro Zone',
'135': 'Boro Zone',
'136': 'Boro Zone',
'137': 'Yellow Zone',
'138': 'Airports',
'139': 'Boro Zone',
'140': 'Yellow Zone',
'141': 'Yellow Zone',
'142': 'Yellow Zone',
'143': 'Yellow Zone',
'144': 'Yellow Zone',
'145': 'Boro Zone',
'146': 'Boro Zone',
'147': 'Boro Zone',
'148': 'Yellow Zone',
'149': 'Boro Zone',
'150': 'Boro Zone',
'151': 'Yellow Zone',
'152': 'Boro Zone',
'153': 'Boro Zone',
'154': 'Boro Zone',
'155': 'Boro Zone',
'156': 'Boro Zone',
'157': 'Boro Zone',
'158': 'Yellow Zone',
'159': 'Boro Zone',
'160': 'Boro Zone',
'161': 'Yellow Zone',
'162': 'Yellow Zone',
'163': 'Yellow Zone',
'164': 'Yellow Zone',
'165': 'Boro Zone',
'166': 'Boro Zone',
'167': 'Boro Zone',
'168': 'Boro Zone',
'169': 'Boro Zone',
'170': 'Yellow Zone',
'171': 'Boro Zone',
'172': 'Boro Zone',
'173': 'Boro Zone',
'174': 'Boro Zone',
'175': 'Boro Zone',
'176': 'Boro Zone',
'177': 'Boro Zone',
'178': 'Boro Zone',
'179': 'Boro Zone',
'180': 'Boro Zone',
'181': 'Boro Zone',
'182': 'Boro Zone',
'183': 'Boro Zone',
'184': 'Boro Zone',
'185': 'Boro Zone',
'186': 'Yellow Zone',
'187': 'Boro Zone',
'188': 'Boro Zone',
'189': 'Boro Zone',
'190': 'Boro Zone',
'191': 'Boro Zone',
'192': 'Boro Zone',
'193': 'Boro Zone',
'194': 'Yellow Zone',
'195': 'Boro Zone',
'196': 'Boro Zone',
'197': 'Boro Zone',
'198': 'Boro Zone',
'199': 'Boro Zone',
'200': 'Boro Zone',
'201': 'Boro Zone',
'202': 'Boro Zone',
'203': 'Boro Zone',
'204': 'Boro Zone',
'205': 'Boro Zone',
'206': 'Boro Zone',
'207': 'Boro Zone',
'208': 'Boro Zone',
'209': 'Yellow Zone',
'210': 'Boro Zone',
'211': 'Yellow Zone',
'212': 'Boro Zone',
'213': 'Boro Zone',
'214': 'Boro Zone',
'215': 'Boro Zone',
'216': 'Boro Zone',
'217': 'Boro Zone',
'218': 'Boro Zone',
'219': 'Boro Zone',
'220': 'Boro Zone',
'221': 'Boro Zone',
'222': 'Boro Zone',
'223': 'Boro Zone',
'224': 'Yellow Zone',
'225': 'Boro Zone',
'226': 'Boro Zone',
'227': 'Boro Zone',
'228': 'Boro Zone',
'229': 'Yellow Zone',
'230': 'Yellow Zone',
'231': 'Yellow Zone',
'232': 'Yellow Zone',
'233': 'Yellow Zone',
'234': 'Yellow Zone',
'235': 'Boro Zone',
'236': 'Yellow Zone',
'237': 'Yellow Zone',
'238': 'Yellow Zone',
'239': 'Yellow Zone',
'240': 'Boro Zone',
'241': 'Boro Zone',
'242': 'Boro Zone',
'243': 'Boro Zone',
'244': 'Boro Zone',
'245': 'Boro Zone',
'246': 'Yellow Zone',
'247': 'Boro Zone',
'248': 'Boro Zone',
'249': 'Yellow Zone',
'250': 'Boro Zone',
'251': 'Boro Zone',
'252': 'Boro Zone',
'253': 'Boro Zone',
'254': 'Boro Zone',
'255': 'Boro Zone',
'256': 'Boro Zone',
'257': 'Boro Zone',
'258': 'Boro Zone',
'259': 'Boro Zone',
'260': 'Boro Zone',
'261': 'Yellow Zone',
'262': 'Yellow Zone',
'263': 'Yellow Zone'
}


rate_code_mapping = {
    1: 'Standard Rate',
    2: 'JFK',
    3: 'Newark',
    4: 'Nassau or Westchester',
    5: 'Negotiated Fare',
    6: 'Group ride'
}

App_company_mapping= {
    'HV0002': 'Juno',
    'HV0003': 'Uber',
    'HV0004': 'Via',
    'HV0005': 'Lyft'
}

trip_type_mapping={
    1: 'Street-hail',
    2: 'Dispatch'
}

payment_type_mapping = {
    1: 'Credit card',
    2: 'Cash',
    3: 'No charge',
    4: 'Dispute',
    5: 'Unknown',
    6: 'Voided trip'
}

def lambda_handler(event, context):
    output = []

    for record in event['records']:

        payload = base64.b64decode(record['data']).decode('utf-8')

        # Transform json payload into python dict
        data_dict = json.loads(payload)

        # Add new column 'Type' with the value of the partitionKey
        data_dict['car_type'] = record['kinesisRecordMetadata']['partitionKey']

        
        if 'tpep_pickup_datetime' in data_dict and 'tpep_dropoff_datetime' in data_dict:

            # add trip_duration with the start date - the end date
            start_date = datetime.fromtimestamp(data_dict['tpep_pickup_datetime'] / 1e3)
            end_date = datetime.fromtimestamp(data_dict['tpep_dropoff_datetime'] / 1e3)
        
            trip_duration = end_date - start_date

            data_dict['trip_duration_minutes'] = trip_duration.total_seconds() / 60
            
            data_dict['pickup_datetime'] = start_date.isoformat()
            
            data_dict['dropoff_datetime'] = end_date.isoformat()
            
        if 'lpep_pickup_datetime' in data_dict and 'lpep_dropoff_datetime' in data_dict:

            # Add a uuid which is the value of the start date - the end date with a prefix
            start_date = datetime.fromtimestamp(data_dict['lpep_pickup_datetime'] / 1e3)
            end_date = datetime.fromtimestamp(data_dict['lpep_dropoff_datetime'] / 1e3)
        
            trip_duration = end_date - start_date

            data_dict['trip_duration_minutes'] = trip_duration.total_seconds() / 60
            
            data_dict['pickup_datetime'] = start_date.isoformat()
            
            data_dict['dropoff_datetime'] = end_date.isoformat()    

        if 'RatecodeID' in data_dict:

            # Map the rate code IDs to their names
            data_dict['RatecodeID'] = rate_code_mapping.get(data_dict['RatecodeID'], 'Unknown Rate Code')

        if 'payment_type' in data_dict:

            # Map the payment type IDs to their names
            data_dict['payment_type'] = payment_type_mapping.get(data_dict['payment_type'], 'Unknown Payment Type')

        if 'Trip_type' in data_dict:

            # Map the trip type IDs to their names
            data_dict['Trip_type'] = trip_type_mapping.get(data_dict['Trip_type'], 'Unknown Trip Type')
        
        if 'Hvfhs_license_num' in data_dict:

            # Map the Hvfhs license num to their names
            data_dict['App_Company'] = trip_type_mapping.get(str(data_dict['Hvfhs_license_num']), 'Unknown App Company')

        if 'PULocationID' in data_dict:

            # Map the location IDs to their names
            data_dict['Pick_up_location'] = location_mapping.get(str(data_dict['PULocationID']), 'Unknown Location')
        
            # Map the location IDs to their Zone names
            data_dict['Pick_up_zone'] = Zone_mapping.get(str(data_dict['PULocationID']), 'Unknown Zone')
              
            # Map the location IDs to their Zone category
            data_dict['Pick_up_zone_category'] = service_zone_mapping.get(str(data_dict['PULocationID']), 'Unknown category')
        
        if 'DOLocationID' in data_dict:
            
            data_dict['Drop_off_location'] = location_mapping.get(str(data_dict['DOLocationID']), 'Unknown Location')
            data_dict['Drop_off_zone'] = Zone_mapping.get(str(data_dict['DOLocationID']), 'Unknown Zone')
            data_dict['Drop_off_zone_category'] = service_zone_mapping.get(str(data_dict['DOLocationID']), 'Unknown category')


        # Re-encode the payload
        payload = base64.b64encode(json.dumps(data_dict).encode('utf-8')).decode('utf-8')

        output_record = {
            'recordId': record['recordId'],
            'result': 'Ok',
            'data': payload
        }
        output.append(output_record)

    print('Successfully processed {} records.'.format(len(output)))

    return {'records': output}
